#!/bin/bash

# Generate .env file with ALL canister IDs for the frontend
# Run this AFTER `dfx deploy`

echo "🔧 Generating environment variables..."

# Get network (default: local)
NETWORK="${DFX_NETWORK:-local}"

# Read canister IDs from dfx
BACKEND_ID=$(dfx canister id voting_backend 2>/dev/null)
II_ID=$(dfx canister id internet_identity 2>/dev/null)
FRONTEND_ID=$(dfx canister id voting_frontend 2>/dev/null)

if [ -z "$BACKEND_ID" ]; then
    echo "❌ Could not get voting_backend canister ID. Did you run 'dfx deploy'?"
    exit 1
fi

if [ -z "$II_ID" ]; then
    echo "⚠️  Could not get internet_identity canister ID. Deploy it with: dfx deploy internet_identity"
fi

# Write root .env (used by vite.config.js)
cat > .env << EOF
# Generated by generate-env.sh — do not edit manually
# Run: bash generate-env.sh (after dfx deploy)

DFX_NETWORK='${NETWORK}'
CANISTER_ID_VOTING_BACKEND='${BACKEND_ID}'
CANISTER_ID_VOTING_FRONTEND='${FRONTEND_ID}'
CANISTER_ID_INTERNET_IDENTITY='${II_ID}'
CANISTER_ID='${BACKEND_ID}'
EOF

echo ""
echo "✅ Environment variables written to .env"
echo ""
echo "   DFX_NETWORK              = ${NETWORK}"
echo "   CANISTER_ID_VOTING_BACKEND   = ${BACKEND_ID}"
echo "   CANISTER_ID_VOTING_FRONTEND  = ${FRONTEND_ID}"
echo "   CANISTER_ID_INTERNET_IDENTITY = ${II_ID}"
echo ""

if [ "$NETWORK" = "local" ]; then
    echo "🌐 Frontend URL:  http://127.0.0.1:4943/?canisterId=${FRONTEND_ID}"
    echo "🔑 Internet Identity URL: http://${II_ID}.localhost:4943"
    echo ""
fi

echo "🚀 Now start the frontend:  cd src/voting_frontend && npm run dev"
